### ISSUE TITLE
How mount Tag using Meteor?

### ISSUE THREAD

**Issue by jadsonlourenco** [xaiki/meteor-riotjs#2]
First thanks for this package!

Well, I create a simple Tag for example:

```
<email>
    <h2>Input Email - {opts.test}</h2>

    this.on('mount', function() {
        console.log('test');
    });
</email>
```

But I don't know how mount this tag on Meteor callback, like on "rendered". If I run in console `riot.mount('email', {test: 0});` this works and load this Tag, but I need to know how do that with Meteor.

Thank you.

**Comment by xaiki** [comment]
Run it exactly as you suggested, in the render callback installing the tag mountpoint.

—
Sent from Mobile,
I shalt be brief

**Comment by xaiki** [comment]
You can have a look here for more details,
https://github.com/xaiki/meteor-riotjs-demo

—
Sent from Mobile,
I shalt be brief

**Comment by jadsonlourenco** [comment]
Yes! I think I made some thing wrong first time, so sorry.

Now I will think more how to use this Riots Tags as components, now I'm using Polymer, but compatibility is so hard to fix¬¬ 

Thank you!
