### ISSUE TITLE
Update Riot.js Version

### ISSUE THREAD

**Issue by praneybehl** [xaiki/meteor-riotjs#3]
Hi thanks for creating the package, since riot.js is now 2.1, would you be able to update the package with the latest riot.js version?

Cheers!

**Comment by endows** [comment]
I reading source code.This package using NPM's compiler.
`var riot = Npm.require('riot');`
https://github.com/xaiki/meteor-riotjs/blob/master/plugin/compile-riot.js

**Comment by endows** [comment]
But Npm config is `"2.0.7"`

`var riotVersion = "2.0.7";`
https://github.com/xaiki/meteor-riotjs/blob/master/package.js

I think that you can use 2.1 when edit `package.js`.

**Comment by endows** [comment]
I forked this repo.And edit `riotVersion` to `2.2.1`.
Why don’t you use it.
https://github.com/endows/meteor-riotjs

But this code is not test.

**Comment by xaiki** [comment]
@endows if interested please take over this project, i'm clearly not maintaining it.
